"""empty message

Revision ID: cbe00d533d46
Revises: e8cc359e1354
Create Date: 2024-06-21 12:46:41.172941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe00d533d46'
down_revision = 'e8cc359e1354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('apply_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('hidden_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('hidden_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('apply_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
