"""Add hidden status to Job

Revision ID: e8cc359e1354
Revises: 51f2aea19bcb
Create Date: 2024-06-21 11:59:58.858408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cc359e1354'
down_revision = '51f2aea19bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('hidden_status')

    # ### end Alembic commands ###
