"""Split details into location and company name

Revision ID: efcad361e7b0
Revises: 7483d7cd80f5
Create Date: 2023-12-21 01:07:42.683782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcad361e7b0'
down_revision = '7483d7cd80f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.drop_column('details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
